[package]
name = "stick-to-rust"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []
cpp = []
swift = []

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.86"
