[package]
name = "hi-ffi"
version = "0.10.0"
edition = "2024"
license = "MIT"
description = "Procedural macro that automatically generates FFI for C++, Python, Swift and Java"
repository = "https://github.com/sbag13/hi-ffi"
keywords = ["ffi", "c++", "python", "swift", "java", "bindings"]

[lib]
proc-macro = true

[features]
default = []
cpp = []
swift = []
python = []
java = []

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0.44"
proc-macro2 = "1.0.86"
