#pragma once
void assert_structs();
void assert_struct_impl_block();
void assert_struct_methods_with_structs();
void assert_struct_methods_with_vectors();
void assert_functions();
void assert_vectors();
void assert_enums();
void assert_results();
void assert_options();
void assert_traits();
